<a href="https://colab.research.google.com/github/tendolkarurja/IPD_Finance/blob/main/model_apply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd

In [26]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [27]:
df = pd.read_csv('/content/drive/MyDrive/final_audit_df.csv')

In [28]:
df

,Date,Headline,Headline link,company
0,2022-01-03,Reliance becomes promoter in Sterling and Wils...,https://economictimes.indiatimes.com/industry/...,reliance
1,2022-01-04,Sterling and Wilson Renewable rise 2% as Relia...,https://economictimes.indiatimes.com/markets/s...,reliance
2,2022-01-11,Biggest gainers & losers of the day: Voda Idea...,https://economictimes.indiatimes.com/markets/s...,adani
3,2022-01-12,DERC turns down city discoms’ request to relin...,https://economictimes.indiatimes.com/industry/...,ntpc
4,2022-01-13,Reliance signs agreement with Gujarat to inves...,https://economictimes.indiatimes.com/industry/...,reliance
...,...,...,...,...
811,2025-06-02,Honeywell signs pact with NTPC Green to explor...,https://economictimes.indiatimes.com/industry/...,ntpc
812,2025-06-05,JSW Energy commissions 281 MW renewable energy...,https://economictimes.indiatimes.com/industry/...,jsw
813,2025-06-06,"NTPC Group installed capacity stands at 80,265...",https://economictimes.indiatimes.com/industry/...,ntpc
814,2025-06-06,JSW Energy shares in focus on commissioning 28...,https://economictimes.indiatimes.com/markets/s...,jsw
815,2025-06-09,"NTPC Group starts Nokh Solar PV Project, total...",https://economictimes.indiatimes.com/industry/...,ntpc

In [29]:
!pip install transformers torch

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [30]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification,pipeline

In [33]:
sentiment_pipe = pipeline("sentiment-analysis", model="ProsusAI/finbert", top_k=None)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [34]:
sentiment_pipe

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [35]:
def generate_scores(text):
    try:
        results = sentiment_pipe(text[:512])
        if isinstance(results[0], list):
            return {item['label'].lower(): item['score'] for item in results[0]}

        elif isinstance(results[0], dict):
            output = {'positive': 0.0, 'negative': 0.0, 'neutral': 0.0}
            label = results[0]['label'].lower()
            output[label] = results[0]['score']
            return output

    except Exception as e:
        return {'positive': 0.0, 'negative': 0.0, 'neutral': 1.0}

# Now run the apply again
print("Processing headlines with the robust function...")
scores_df = df['Headline'].apply(generate_scores).apply(pd.Series)

Processing headlines with the robust function...

In [36]:
scores_df

      neutral  positive  negative
0    0.901476  0.088610  0.009914
1    0.027760  0.947282  0.024958
2    0.198752  0.639171  0.162076
3    0.800283  0.079145  0.120572
4    0.062623  0.925366  0.012011
..        ...       ...       ...
811  0.105759  0.884972  0.009269
812  0.910477  0.074887  0.014636
813  0.896316  0.094371  0.009313
814  0.204826  0.787782  0.007392
815  0.623435  0.366464  0.010101

[816 rows x 3 columns]

In [37]:
df_withScores = pd.concat([df, scores_df], axis=1)

In [38]:
df_withScores

,Date,Headline,Headline link,company,neutral,positive,negative
0,2022-01-03,Reliance becomes promoter in Sterling and Wils...,https://economictimes.indiatimes.com/industry/...,reliance,0.901476,0.088610,0.009914
1,2022-01-04,Sterling and Wilson Renewable rise 2% as Relia...,https://economictimes.indiatimes.com/markets/s...,reliance,0.027760,0.947282,0.024958
2,2022-01-11,Biggest gainers & losers of the day: Voda Idea...,https://economictimes.indiatimes.com/markets/s...,adani,0.198752,0.639171,0.162076
3,2022-01-12,DERC turns down city discoms’ request to relin...,https://economictimes.indiatimes.com/industry/...,ntpc,0.800283,0.079145,0.120572
4,2022-01-13,Reliance signs agreement with Gujarat to inves...,https://economictimes.indiatimes.com/industry/...,reliance,0.062623,0.925366,0.012011
...,...,...,...,...,...,...,...
811,2025-06-02,Honeywell signs pact with NTPC Green to explor...,https://economictimes.indiatimes.com/industry/...,ntpc,0.105759,0.884972,0.009269
812,2025-06-05,JSW Energy commissions 281 MW renewable energy...,https://economictimes.indiatimes.com/industry/...,jsw,0.910477,0.074887,0.014636
813,2025-06-06,"NTPC Group installed capacity stands at 80,265...",https://economictimes.indiatimes.com/industry/...,ntpc,0.896316,0.094371,0.009313
814,2025-06-06,JSW Energy shares in focus on commissioning 28...,https://economictimes.indiatimes.com/markets/s...,jsw,0.204826,0.787782,0.007392
815,2025-06-09,"NTPC Group starts Nokh Solar PV Project, total...",https://economictimes.indiatimes.com/industry/...,ntpc,0.623435,0.366464,0.010101

In [39]:
# Test with a complex headline that should have mixed sentiment
test_headline = "Adani shares rise despite ongoing regulatory concerns"
raw_output = sentiment_pipe(test_headline)

print("--- RAW MODEL OUTPUT ---")
print(raw_output)

--- RAW MODEL OUTPUT ---
[[{'label': 'positive', 'score': 0.9356290698051453}, {'label': 'negative', 'score': 0.039950791746377945}, {'label': 'neutral', 'score': 0.024420147761702538}]]

In [40]:
df_withScores['cumulative_score'] = df_withScores['positive'] - df_withScores['negative']
df_withScores

,Date,Headline,Headline link,company,neutral,positive,negative,cumulative_score
0,2022-01-03,Reliance becomes promoter in Sterling and Wils...,https://economictimes.indiatimes.com/industry/...,reliance,0.901476,0.088610,0.009914,0.078695
1,2022-01-04,Sterling and Wilson Renewable rise 2% as Relia...,https://economictimes.indiatimes.com/markets/s...,reliance,0.027760,0.947282,0.024958,0.922324
2,2022-01-11,Biggest gainers & losers of the day: Voda Idea...,https://economictimes.indiatimes.com/markets/s...,adani,0.198752,0.639171,0.162076,0.477095
3,2022-01-12,DERC turns down city discoms’ request to relin...,https://economictimes.indiatimes.com/industry/...,ntpc,0.800283,0.079145,0.120572,-0.041427
4,2022-01-13,Reliance signs agreement with Gujarat to inves...,https://economictimes.indiatimes.com/industry/...,reliance,0.062623,0.925366,0.012011,0.913355
...,...,...,...,...,...,...,...,...
811,2025-06-02,Honeywell signs pact with NTPC Green to explor...,https://economictimes.indiatimes.com/industry/...,ntpc,0.105759,0.884972,0.009269,0.875704
812,2025-06-05,JSW Energy commissions 281 MW renewable energy...,https://economictimes.indiatimes.com/industry/...,jsw,0.910477,0.074887,0.014636,0.060251
813,2025-06-06,"NTPC Group installed capacity stands at 80,265...",https://economictimes.indiatimes.com/industry/...,ntpc,0.896316,0.094371,0.009313,0.085058
814,2025-06-06,JSW Energy shares in focus on commissioning 28...,https://economictimes.indiatimes.com/markets/s...,jsw,0.204826,0.787782,0.007392,0.780390
815,2025-06-09,"NTPC Group starts Nokh Solar PV Project, total...",https://economictimes.indiatimes.com/industry/...,ntpc,0.623435,0.366464,0.010101,0.356363

In [42]:
df_withScores.to_csv('finbert_scores_ESG.csv', index= False)